### ISSUE TITLE
AttributeError: 'ValuesArguments' object has no attribute 'argument_node'

### ISSUE THREAD

**Issue by baumanno** [vheon/JediHTTP#51] opened 2018-01-11 23:42 UTC
Hi!
Using JediHTTP with YouCompleteMe in Vim, I'm not getting completions for the python lib [networkx](https://github.com/networkx/networkx). It seems that there is a parsing issue with the response from jedi leading to the error in the title, subsequently failing to generate a list of completion candidates. I have tracked this issue down to be 99% with JediHTTP, as I was able to get completions for jedi via its Python-API (i.e. via "import jedi").

A test case and the full stack trace follow below. 

## Test case
```bash
# I did this in a virtualenv, but systemwide is the same
$ pip install networkx
$ .venv/bin/python /path/to/jedihttp.py --port 38241 &
$ curl -X POST 127.0.0.1:38241/completions \
    -H 'content-type: application/json' \
    -d '{"source": "import networkx as nx\n\ng = nx.G\n",
        "line": 3,
        "col": 7,
        "source_path": "/home/baumanno/code/foo.py"}'
# The result of this call is an error containing the stack trace;
# the output of the jedihttp.py call is, again, the stack trace

# This call, however, succeeds!
$ curl -X POST 127.0.0.1:38241/completions \
    -H 'content-type: application/json' \
    -d '{"source": "import networkx as nx\n\ng = nx.G\n",
        "line": 3,
        "col": 8,
        "source_path": "/home/baumanno/code/foo.py"}'
```

As you can see, something seems to be amiss with the column number. It may well be that it is an issue with networkx itself, but I can't tell. I'll be happy to provide further information if required!

## Jedi lib
For completeness, here is the jedi-only code that works:

```python
import jedi

script = '''import networkx as nx

g = nx.G'''
# both of these work and list different sets of completions
jedi.Script(script, 3, 7).completions()
jedi.Script(script, 3, 8).completions()
```
## Stacktrace
```
python .venv/bin/python /path/to/jedihttp.py --port 38241 --log=debug
serving on http://127.0.0.1:38241
2018-01-12 00:02:06,176 - DEBUG - received /completions request
2018-01-12 00:02:17,834 - DEBUG - received /completions request
Traceback (most recent call last):
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/bottle/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/jedihttp/handlers.py", line 66, in completions
    response = _format_completions(script.completions())
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/jedihttp/handlers.py", line 155, in _format_completions
    } for completion in completions]
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/jedihttp/handlers.py", line 155, in <listcomp>
    } for completion in completions]
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/api/classes.py", line 148, in type
    for context in self._name.infer():
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/filters.py", line 97, in infer
    return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 231, in _name_to_types
    types = imports.infer_import(context, tree_name)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/imports.py", line 75, in infer_import
    ) for t in types
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/common.py", line 105, in unite
    return set(typ for types in iterable for typ in types)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/common.py", line 105, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/imports.py", line 75, in <genexpr>
    ) for t in types
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/_compatibility.py", line 212, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/context.py", line 63, in py__getattribute__
    analysis_errors)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 159, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 68, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 163, in _names_to_types
    types = unite(name.infer() for name in names)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/common.py", line 105, in unite
    return set(typ for types in iterable for typ in types)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/common.py", line 105, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 163, in <genexpr>
    types = unite(name.infer() for name in names)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/filters.py", line 97, in infer
    return _name_to_types(self.parent_context.evaluator, self.parent_context, self.tree_name)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 233, in _name_to_types
    types = _apply_decorators(evaluator, context, node)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 281, in _apply_decorators
    for dec_value in dec_values)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/common.py", line 105, in unite
    return set(typ for types in iterable for typ in types)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/common.py", line 105, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 281, in <genexpr>
    for dec_value in dec_values)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/context.py", line 36, in execute
    return self.evaluator.execute(self, arguments)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 465, in execute
    types = func(arguments)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/representation.py", line 275, in py__call__
    return self.infer_function_execution(function_execution)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/representation.py", line 265, in infer_function_execution
    return function_execution.get_return_values()
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/recursion.py", line 83, in wrapper
    result = func(execution, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/representation.py", line 343, in get_return_values
    types |= self.eval_node(children[1])
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/context.py", line 47, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 282, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 294, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 298, in _eval_element_cached
    return self._eval_element_not_cached(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 107, in wrapper
    return func(evaluator, context, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 326, in _eval_element_not_cached
    types = self.eval_trailer(context, types, trailer)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 443, in eval_trailer
    new_types |= self.execute(typ, arguments)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 465, in execute
    types = func(arguments)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/representation.py", line 275, in py__call__
    return self.infer_function_execution(function_execution)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/representation.py", line 265, in infer_function_execution
    return function_execution.get_return_values()
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/recursion.py", line 83, in wrapper
    result = func(execution, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/representation.py", line 343, in get_return_values
    types |= self.eval_node(children[1])
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/context.py", line 47, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 282, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 294, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 298, in _eval_element_cached
    return self._eval_element_not_cached(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 107, in wrapper
    return func(evaluator, context, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 307, in _eval_element_not_cached
    types = self.eval_atom(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 378, in eval_atom
    search_global=True
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/_compatibility.py", line 212, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/context.py", line 63, in py__getattribute__
    analysis_errors)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 159, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 60, in find
    names = self.filter_name(filters)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 125, in filter_name
    names = filter.get(self._string_name)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/filters.py", line 167, in get
    return self._convert_names(self._filter(names))
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/filters.py", line 199, in _filter
    return list(self._check_flows(names))
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/filters.py", line 213, in _check_flows
    self._node_context, self._parser_scope, name, self._origin_scope
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/flow_analysis.py", line 76, in reachability_check
    return _break_check(context, context_scope, first_flow_scope, node)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/flow_analysis.py", line 84, in _break_check
    reachable = _check_if(context, check_node)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/flow_analysis.py", line 107, in _check_if
    types = context.eval_node(node)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/context.py", line 47, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 277, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 294, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 298, in _eval_element_cached
    return self._eval_element_not_cached(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 107, in wrapper
    return func(evaluator, context, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 358, in _eval_element_not_cached
    types = precedence.calculate_children(self, context, element.children)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/precedence.py", line 44, in calculate_children
    types = context.eval_node(next(iterator))
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/context.py", line 47, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 277, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 294, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 298, in _eval_element_cached
    return self._eval_element_not_cached(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 107, in wrapper
    return func(evaluator, context, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 307, in _eval_element_not_cached
    types = self.eval_atom(context, element)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 378, in eval_atom
    search_global=True
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/_compatibility.py", line 212, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/context.py", line 63, in py__getattribute__
    analysis_errors)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/__init__.py", line 159, in find_types
    return f.find(filters, attribute_lookup=not search_global)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 68, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 163, in _names_to_types
    types = unite(name.infer() for name in names)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/common.py", line 105, in unite
    return set(typ for types in iterable for typ in types)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/common.py", line 105, in <genexpr>
    return set(typ for types in iterable for typ in types)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/finder.py", line 163, in <genexpr>
    types = unite(name.infer() for name in names)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/filters.py", line 115, in infer
    return self.get_param().infer()
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/filters.py", line 118, in get_param
    params = self.parent_context.get_params()
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/representation.py", line 419, in get_params
    return self.var_args.get_params(self)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/param.py", line 80, in get_params
    return get_params(execution_context, self)
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/param.py", line 322, in get_params
    for node in var_args.get_calling_nodes():
  File "/home/baumanno/dotfiles/vim/pack/plugins/start/YouCompleteMe/third_party/ycmd/third_party/JediHTTP/vendor/jedi/jedi/evaluate/param.py", line 210, in get_calling_nodes
    return [arguments.argument_node or arguments.trailer]
AttributeError: 'ValuesArguments' object has no attribute 'argument_node'
```

**Comment by vheon** [comment] 2018-01-12 22:30
Thanks for de detailed report! I'll try to look into this during the week end 👍

**Comment by micbou** [comment] 2018-01-12 23:55
I already looked into it and it's in fact an issue with Jedi that occurs when getting [the docstring of `complete_bipartite_graph`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/bipartite/generators.py#L35) in `networkx`. This can be reproduced with the following code:
```python
import jedi

for completion in jedi.Script("import networkx; networkx.").completions():
  completion.docstring()
```
I opened [a PR that fixes the issue on Jedi repository](https://github.com/davidhalter/jedi/pull/1026) (though I am not sure it's the right way to fix it).

**Comment by vheon** [comment] 2018-01-15 13:18
@micbou Thanks a bunch!

**Comment by vheon** [comment] 2018-01-15 21:30
@micbou I saw that your PR was already merged in but it looks like some clean up is still in progress around that area, so I would prefer to wait before updating jedi. I don't know how common this problem is and how urgent it is to fix 😕

**Comment by micbou** [comment] 2018-01-15 21:45
Yes, Jedi master branch is currently broken so we need to wait before updating it in JediHTTP. I think I am going to prepare a PR with a workaround for that issue and https://github.com/vheon/JediHTTP/issues/46.

**Comment by micbou** [comment] 2018-01-15 22:18
Actually, the workaround doesn't work for that issue so let's just wait.

**Comment by micbou** [comment] 2018-06-20 18:07
Fixed by PR https://github.com/Valloric/ycmd/pull/1028.

**Closed as completed by micbou** 2018-06-20 18:07 UTC
